dynamia:
  app:
    name: Dynamia Chronos (beta)
    author: @project.organization.name@
    version: @project.version@
    template: Dynamical
    default-skin: dracula
    base-package: tools.dynamia
    default-logo: /static/chronos-logo-light.png
    default-icon: /static/chronos-icon.png




spring:
  application:
    name: Dynamia Chronos


  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/dynamiachronos}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:

    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

